name: macrotic
description: Macros are awesome!
version: 1.0.2
repository: https://github.com/ArcaneArts/macrotic
environment:
  sdk: ^3.5.0-167
dependencies:
  collection: ^1.19.0
  macros: ^0.1.0-main.5
